### ISSUE TITLE
Magic Numbers

### ISSUE THREAD

**Issue by SkrytnayaRediska** [ZenyaBelkov/Homework_lesson_12#1]
https://github.com/ZenyaBelkov/Homework_lesson_12/blob/dd2216f676fc08dcdd43b084827c0f6941de07ff/venv/homework_lesson_12.py#L12

why comparing strange numbers in elif section? what is 16 and so one? Probably need to create some constants for the imt boarders

**Comment by ZenyaBelkov** [comment]
Fixed in a new brunch https://github.com/ZenyaBelkov/Homework_lesson_12/blob/1-magic-numbers/venv/homework_lesson_12.py
